=== qt4cg/qt4tests/fn/system-properties/supports-dtd.dtd
<!ENTITY redteammotto "Strengthened through the challenge">

<!ELEMENT employees (employee)+>

<!ELEMENT employee (first,last,(deputy|manager), motto)>
<!ATTLIST employee
    id ID #REQUIRED>

<!ELEMENT first (#PCDATA)>

<!ELEMENT last (#PCDATA)>

<!ELEMENT deputy (#PCDATA)>
<!ATTLIST deputy
    ref IDREF #REQUIRED>

<!ELEMENT manager (#PCDATA)>
<!ATTLIST manager
    ref IDREF #REQUIRED>
    
<!ELEMENT motto (#PCDATA)>

=== qt4cg/qt4tests/fn/system-properties/supports-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "supports-dtd.dtd">
<employees>
	<employee id="E21256">
		<first>Anil</first>
		<last>Singh</last>
		<deputy ref="E30561" />
		<motto>&redteammotto;</motto>
	</employee>
	<employee id="E30561">
		<first>Anila</first>
		<last>Kaur</last>
		<manager ref="E21256" />
		<motto>&redteammotto;</motto>
	</employee>
</employees>
